---
root: true

extends:
  # https://github.com/facebook/create-react-app/tree/master/packages/eslint-config-react-app
  - react-app
  # https://github.com/yannickcr/eslint-plugin-react
  - plugin:react/recommended
  # https://github.com/gajus/eslint-plugin-flowtype
  - plugin:flowtype/recommended
  # https://www.npmjs.com/package/eslint-plugin-jest
  - plugin:jest/recommended
  # https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin
  - plugin:@typescript-eslint/recommended
  # https://github.com/prettier/eslint-config-prettier
  - prettier
  # https://github.com/gajus/eslint-plugin-flowtype
  - prettier/flowtype
  # https://github.com/typescript-eslint/typescript-eslint
  - prettier/@typescript-eslint
  # https://github.com/yannickcr/eslint-plugin-react
  - prettier/react

plugins:
  # https://www.npmjs.com/package/eslint-plugin-jest
  - jest
  # https://github.com/prettier/eslint-plugin-prettier
  - prettier

env:
  jasmine: true
  jest: true
  jest/globals: true # https://www.npmjs.com/package/eslint-plugin-jest#usage
  shared-node-browser: true

rules:
  prettier/prettier:
    - error
    -
      trailingComma: all
      bracketSpacing: false

  ### Styling ###

  # Prefer new line before return
  # http://eslint.org/docs/rules/newline-before-return
  newline-before-return: error # airbnb default: off

  ### Best practices ###
  # require or disallow Yoda conditions
  # https://eslint.org/docs/rules/yoda
  yoda: [error, never, { exceptRange: true }] # airbnb default: 'error'

  # add culry braces all the time
  # https://eslint.org/docs/rules/curly
  curly: [error, all] # airbnb default: [error, multi-line]

  ### Import ###

  # Require modules with a single export to use a default export
  # https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/prefer-default-export.md
  import/prefer-default-export: off # airbnb default: 'error'

  ### Debugging is allowed but not allowed to commit ###
  no-console: warn # airbnb default: 'error'
  no-debugger: warn # airbnb default: 'error'

  ### React ###
  # do not force jsx use js
  # https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md
  react/jsx-filename-extension: off

  # Require stateless functions when not using lifecycle methods, setState or ref
  # https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md
  react/prefer-stateless-function: warn # airbnb default: 'error'

  ### Removed rules
  # no longer defined
  jsx-a11y/href-no-hash: off

  # Solves inline snapshots complains, leave this to prettier
  # https://eslint.org/docs/rules/no-irregular-whitespace
  no-irregular-whitespace:
    - off

  # Build and other not compiled files should have option to use require
  # https://github.com/bradzacher/eslint-plugin-typescript/blob/master/docs/rules/no-var-requires.md
  "@typescript-eslint/no-var-requires": off
