language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - node_modules

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - "yarn run test:coverage"

jobs:
  include:
    - stage: checks
      script:
        - commitlint-travis
        - "yarn run lint"
        - "yarn run test:coverage"

    - stage: lerna publish
      # require the branch name to be master
      if: branch = master
      deploy:
        - provider: script
          script: "yarn run lerna:publish"
          skip_cleanup: true
          on:
            tags: true
            branch: master
            node: "10"

        - provider: script
          script: yarn run deploy --repo https://$GITHUB_TOKEN@github.com/ableneo/tools.git
          github_token: $GITHUB_TOKEN
          skip_cleanup: true
          keep_history: true
          on:
            tags: true
            branch: master
            node: "10"

