language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - commitlint-travis
  - "yarn run lint"
  - "yarn run test:coverage"
cache:
  yarn: true
  directories:
    - node_modules

deploy:
  provider: script
  script: yarn run deploy --repo https://$GITHUB_TOKEN@github.com/ableneo/tools.git
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
