language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

after_install:
  - "yarn -v"

script:
  - commitlint-travis
  - "yarn run lint"
  - "yarn run test:coverage"

cache:
  yarn: true
  directories:
    - node_modules

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - "yarn run test:coverage"

jobs:
  include:
    - stage: publish
      # require the branch name to be master
      if: branch = master
      - provider: script
        script: "yarn run lerna:publish"
        skip_cleanup: true
        on:
          tags: true
          branch: master
          node: "10"

      - provider: script
        script: yarn run deploy --repo https://$GITHUB_TOKEN@github.com/ableneo/tools.git
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        keep_history: true
        on:
          tags: true
          branch: master
          node: "10"

